apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/joseps/order-service/k8s?ref=da3a5c865467583045871ab40c3686a5130cf1ff

patchesStrategicMerge:
  - patch-env.yml
  - patch-resources.yml
  - patch-volumes.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yml
    name: order-config

images:
  - name: order-service
    newName: ghcr.io/joseps/order-service
    newTag: latest

replicas:
  - count: 1
    name: order-service
